"""
AI Code DNA Detector — heuristic-based scanner that estimates whether code
was generated by an AI (GPT, Claude, Copilot, etc.) vs written by a human.

Signals used (no LLM required):
  1. Comment density     — AI over-documents with boilerplate JSDoc/docstrings
  2. Avg function length — AI functions tend to be a uniform, medium length
  3. TODO absence rate   — Real devs leave TODOs; AI rarely does
  4. Try-except density  — AI wraps everything defensively
  5. Variable name length— AI uses long descriptive camelCase names
  6. Boilerplate phrases — "This function", "The following", "Note that" etc.
"""

import os
import re
import math

SOURCE_EXTS = {'.py', '.js', '.ts', '.jsx', '.tsx', '.md'}

# Phrases that appear overwhelmingly in AI-generated code comments
BOILERPLATE_PHRASES = [
    r'this function', r'this method', r'the following', r'note that',
    r'please note', r'as you can see', r'in this (example|case|implementation)',
    r'we (first|then|also|need to)', r'here we', r'make sure to',
    r'don\'t forget', r'feel free to', r'you can (also|use|modify)',
    r'this (is|will|ensures|allows)', r'the (above|below) code',
    r'initializes?', r'instantiates?', r'retrieves?'
]

AI_SIGNATURE_PATTERNS = [
    # Explicit AI fingerprints (high-signal)
    r'\b(chatgpt|gpt-?4|gpt-?3\.?5|openai|claude|anthropic|copilot)\b',
    r'\b(as an ai|large language model|llm)\b',
    r'\b(generated by|written by|created by)\s+(chatgpt|gpt|openai|claude|copilot)\b',
    r'\b(generated with|built with|created with)\s+(ai|chatgpt|gpt|openai|claude|copilot)\b',
    r'\b(prompt|system prompt|assistant|model)\b',
]

AI_KEYWORD_IN_PATH = re.compile(r'(chatgpt|gpt|openai|claude|anthropic|copilot)', re.I)

def _shannon_entropy(tokens: list[str]) -> float:
    """Token diversity proxy. Higher = more diverse."""
    if not tokens:
        return 0.0
    counts: dict[str, int] = {}
    for t in tokens:
        counts[t] = counts.get(t, 0) + 1
    n = len(tokens)
    ent = 0.0
    for c in counts.values():
        p = c / n
        ent -= p * math.log2(p)
    return ent

def _analyze_file(content: str) -> dict:
    lines = content.splitlines()
    total_lines = max(len(lines), 1)

    # 1. Comment density
    comment_lines = sum(
        1 for l in lines
        if l.strip().startswith(('#', '//', '*', '/*', '"""', "'''"))
    )
    comment_ratio = comment_lines / total_lines

    # 2. Function count & avg length (approx)
    # Prefer patterns that indicate actual function declarations (avoid matching arbitrary assignments/calls).
    fn_starts = []
    for i, l in enumerate(lines):
        if re.match(r'^\s*def\s+\w+\s*\(', l):
            fn_starts.append(i)
            continue
        if re.match(r'^\s*(export\s+)?(async\s+)?function\s+\w+\s*\(', l):
            fn_starts.append(i)
            continue
        # Arrow function forms: const name = (...) => / name = (...) =>
        if re.match(r'^\s*(export\s+)?(const|let|var)\s+\w+\s*=\s*(async\s*)?\([^)]*\)\s*=>', l):
            fn_starts.append(i)
            continue
        if re.match(r'^\s*\w+\s*=\s*(async\s*)?\([^)]*\)\s*=>', l):
            fn_starts.append(i)

    # 3. TODO/FIXME absence
    has_todos = any(re.search(r'\b(TODO|FIXME|HACK|XXX)\b', l, re.I) for l in lines)

    # 4. Try-except / try-catch density
    try_lines = sum(1 for l in lines if re.match(r'\s*(try\s*{?|except |catch\s*\()', l))
    try_ratio = try_lines / total_lines

    # 5. Variable name length + entropy proxies
    # JS/TS const/let/var
    js_vars = [m[1] for m in re.findall(r'\b(const|let|var)\s+([a-zA-Z_]\w*)', content)]
    # Python assignments at line start (avoid "==" and imports)
    py_vars = [
        m.group(1)
        for m in (re.match(r'^\s*([a-zA-Z_]\w*)\s*=\s*[^=]', l) for l in lines)
        if m and m.group(1) not in {"True", "False", "None"}
    ]
    # Attribute assignments (some signal, lower quality)
    attr_vars = [m[1] for m in re.findall(r'\b(self\.|this\.)\s*([a-zA-Z_]\w*)', content)]
    var_names = js_vars + py_vars + attr_vars

    avg_var_len = (sum(len(v) for v in var_names) / len(var_names)) if var_names else 0.0
    long_var_ratio = (sum(1 for v in var_names if len(v) >= 12) / len(var_names)) if var_names else 0.0
    var_entropy = _shannon_entropy(var_names)

    # 6. Boilerplate phrase count in comments
    comment_text = ' '.join(l for l in lines if l.strip().startswith(('#', '//', '*', '"""', "'''")))
    boilerplate_hits = sum(len(re.findall(p, comment_text, re.I)) for p in BOILERPLATE_PHRASES)

    # 7. AI signature hits (comments OR strings)
    signature_hits = sum(len(re.findall(p, content, re.I)) for p in AI_SIGNATURE_PATTERNS)

    # 8. Function "uniformity": low variance in function sizes can indicate templated generation.
    # Estimate function lengths by distance between consecutive fn starts.
    fn_lengths = []
    for idx, start in enumerate(fn_starts):
        end = fn_starts[idx + 1] if idx + 1 < len(fn_starts) else total_lines
        fn_lengths.append(max(end - start, 0))
    avg_fn_len = (sum(fn_lengths) / len(fn_lengths)) if fn_lengths else 0.0
    if fn_lengths and len(fn_lengths) >= 3:
        mean = avg_fn_len or 1.0
        variance = sum((x - mean) ** 2 for x in fn_lengths) / len(fn_lengths)
        fn_cv = math.sqrt(variance) / mean  # coefficient of variation
    else:
        fn_cv = 1.0  # treat as non-uniform when insufficient data

    return {
        'comment_ratio': comment_ratio,
        'fn_density': len(fn_starts) / total_lines,
        'has_todos': has_todos,
        'try_ratio': try_ratio,
        'avg_var_len': avg_var_len,
        'long_var_ratio': long_var_ratio,
        'var_entropy': var_entropy,
        'boilerplate_hits': boilerplate_hits,
        'signature_hits': signature_hits,
        'avg_fn_len': avg_fn_len,
        'fn_cv': fn_cv,
        'total_lines': total_lines
    }

def _compute_ai_confidence(stats: dict) -> int:
    """Combine signals into 0-100 AI confidence score."""
    score = 0.0

    # High comment ratio (+18 max). Many repos have low comments even if AI-made.
    score += min(stats['comment_ratio'] * 100, 18)

    # No TODOs (+12)
    if not stats['has_todos']:
        score += 12

    # High try density (+12 max)
    score += min(stats['try_ratio'] * 300, 12)

    # Long variable names (+12 max)
    if stats['avg_var_len'] > 10:
        score += min((stats['avg_var_len'] - 10) * 2.5, 12)

    # Lots of long names (+10 max)
    score += min(stats.get('long_var_ratio', 0.0) * 40, 10)

    # Low entropy in variable names (repetitive templating) (+8 max)
    # If entropy is low AND there are variables, it's a small positive AI signal.
    var_entropy = stats.get('var_entropy', 0.0)
    if stats.get('avg_var_len', 0.0) > 0:
        score += min(max(0.0, 3.0 - var_entropy) * 3.0, 8)

    # Boilerplate phrases (+18 max)
    score += min(stats['boilerplate_hits'] * 4, 18)

    # AI signature hits (+55 max) — high-signal when present
    score += min(stats.get('signature_hits', 0) * 22, 55)

    # Function uniformity (+10 max). Lower CV -> more uniform -> more AI-like.
    fn_cv = stats.get('fn_cv', 1.0)
    score += min(max(0.0, 0.9 - fn_cv) * 15, 10)

    return min(int(round(score)), 100)

def scan_ai_dna(extract_dir: str) -> dict:
    """
    Returns a summary dict with overall AI confidence and per-file breakdown.
    Does NOT return issues list — this is a separate top-level metric.
    """
    per_file = []
    IGNORED = {'node_modules', 'venv', '__pycache__', '.git', 'dist', 'build'}

    for root, dirs, files in os.walk(extract_dir):
        dirs[:] = [d for d in dirs if d not in IGNORED and not d.startswith('.')]
        for f in files:
            ext = os.path.splitext(f)[1].lower()
            if ext not in SOURCE_EXTS:
                continue
            path = os.path.join(root, f)
            try:
                with open(path, 'r', encoding='utf-8', errors='ignore') as fh:
                    content = fh.read()
                if len(content.strip()) < 50:
                    continue
                stats = _analyze_file(content)
                confidence = _compute_ai_confidence(stats)
                rel = os.path.relpath(path, extract_dir).replace('\\', '/')
                # Filename/path AI hint (e.g., claude.js, chatgpt_prompt.md)
                if AI_KEYWORD_IN_PATH.search(rel):
                    confidence = min(100, confidence + 20)
                per_file.append({
                    'file': rel,
                    'confidence': confidence,
                    'lines': stats['total_lines']
                })
            except Exception:
                continue

    if not per_file:
        return {
            'version': 'ai-dna-v2.2',
            'overall_confidence': 0,
            'files': [],
            'verdict': 'Unknown',
            'debug': {
                'total_code_lines': 0,
                'moderate_frac': 0.0,
                'strong_frac': 0.0,
                'weighted_mean': 0.0,
            }
        }

    # Aggregate score.
    # A plain average can under-report AI if many low-signal files dilute a few strongly AI-like files.
    total_lines = sum(f['lines'] for f in per_file) or 1
    weighted_mean = sum(f['confidence'] * f['lines'] for f in per_file) / total_lines

    # Fraction-of-lines metric: if most code lines are in moderately/highly AI-like files,
    # we should reflect that in the overall score.
    # Use slightly lower thresholds; the per-file classifier is intentionally conservative.
    moderate_lines = sum(f['lines'] for f in per_file if f['confidence'] >= 45)
    strong_lines = sum(f['lines'] for f in per_file if f['confidence'] >= 70)
    moderate_frac = moderate_lines / total_lines
    strong_frac = strong_lines / total_lines

    frac_score = 20 + 80 * moderate_frac          # 20..100
    frac_boost = 10 * strong_frac                 # 0..10

    # Line-weighted percentile (robust against dilution). Find the confidence where
    # cumulative line coverage crosses 75%.
    per_file_sorted = sorted(per_file, key=lambda x: x['confidence'])
    cum = 0
    p75 = per_file_sorted[-1]['confidence']
    for f in per_file_sorted:
        cum += f['lines']
        if cum / total_lines >= 0.75:
            p75 = f['confidence']
            break

    overall = int(round(max(weighted_mean, p75, min(100.0, frac_score + frac_boost))))

    # Calibration: if a meaningful fraction of lines look strongly AI-like,
    # cap the "likely AI-generated" floor so we don't get stuck in the low 70s.
    max_conf = max(f['confidence'] for f in per_file) if per_file else 0
    if strong_frac >= 0.30 and max_conf >= 90:
        overall = max(overall, 85)

    verdict = (
        'Almost certainly AI-generated' if overall >= 80 else
        'Likely AI-generated' if overall >= 60 else
        'Mixed (Human + AI)' if overall >= 35 else
        'Likely Human-written'
    )

    per_file.sort(key=lambda x: x['confidence'], reverse=True)

    return {
        'version': 'ai-dna-v2.2',
        'overall_confidence': overall,
        'files': per_file[:10],  # top 10 most AI-looking files
        'verdict': verdict,
        'debug': {
            'total_code_lines': int(total_lines),
            'moderate_frac': round(moderate_frac, 4),
            'strong_frac': round(strong_frac, 4),
            'weighted_mean': round(float(weighted_mean), 2),
            'p75': int(p75),
            'max_conf': int(max_conf),
        }
    }
