"""
AI Code DNA Detector — heuristic-based scanner that estimates whether code
was generated by an AI (GPT, Claude, Copilot, etc.) vs written by a human.

Signals used (no LLM required):
  1. Comment density     — AI over-documents with boilerplate JSDoc/docstrings
  2. Avg function length — AI functions tend to be a uniform, medium length
  3. TODO absence rate   — Real devs leave TODOs; AI rarely does
  4. Try-except density  — AI wraps everything defensively
  5. Variable name length— AI uses long descriptive camelCase names
  6. Boilerplate phrases — "This function", "The following", "Note that" etc.
"""

import os
import re

SOURCE_EXTS = {'.py', '.js', '.ts', '.jsx', '.tsx'}

# Phrases that appear overwhelmingly in AI-generated code comments
BOILERPLATE_PHRASES = [
    r'this function', r'this method', r'the following', r'note that',
    r'please note', r'as you can see', r'in this (example|case|implementation)',
    r'we (first|then|also|need to)', r'here we', r'make sure to',
    r'don\'t forget', r'feel free to', r'you can (also|use|modify)',
    r'this (is|will|ensures|allows)', r'the (above|below) code',
    r'initializes?', r'instantiates?', r'retrieves?'
]

def _analyze_file(content: str) -> dict:
    lines = content.splitlines()
    total_lines = max(len(lines), 1)

    # 1. Comment density
    comment_lines = sum(
        1 for l in lines
        if l.strip().startswith(('#', '//', '*', '/*', '"""', "'''"))
    )
    comment_ratio = comment_lines / total_lines

    # 2. Function count & avg length
    fn_starts = [i for i, l in enumerate(lines)
                 if re.match(r'\s*(def |function |const \w+ = |async function |\w+ = \()', l)]

    # 3. TODO/FIXME absence
    has_todos = any(re.search(r'\b(TODO|FIXME|HACK|XXX)\b', l, re.I) for l in lines)

    # 4. Try-except / try-catch density
    try_lines = sum(1 for l in lines if re.match(r'\s*(try\s*{?|except |catch\s*\()', l))
    try_ratio = try_lines / total_lines

    # 5. Average variable name length (from simple assignments)
    var_names = re.findall(r'\b(const|let|var|self\.|this\.)\s+([a-zA-Z_]\w*)', content)
    avg_var_len = (sum(len(v[1]) for v in var_names) / len(var_names)) if var_names else 0

    # 6. Boilerplate phrase count in comments
    comment_text = ' '.join(l for l in lines if l.strip().startswith(('#', '//', '*', '"""', "'''")))
    boilerplate_hits = sum(len(re.findall(p, comment_text, re.I)) for p in BOILERPLATE_PHRASES)

    return {
        'comment_ratio': comment_ratio,
        'fn_density': len(fn_starts) / total_lines,
        'has_todos': has_todos,
        'try_ratio': try_ratio,
        'avg_var_len': avg_var_len,
        'boilerplate_hits': boilerplate_hits,
        'total_lines': total_lines
    }

def _compute_ai_confidence(stats: dict) -> int:
    """Combine signals into 0-100 AI confidence score."""
    score = 0

    # High comment ratio (+25 max)
    score += min(stats['comment_ratio'] * 100, 25)

    # No TODOs (+15)
    if not stats['has_todos']:
        score += 15

    # High try-except density (+15 max)
    score += min(stats['try_ratio'] * 300, 15)

    # Long variable names (+15 max)
    if stats['avg_var_len'] > 10:
        score += min((stats['avg_var_len'] - 10) * 3, 15)

    # Boilerplate phrases (+30 max)
    score += min(stats['boilerplate_hits'] * 5, 30)

    return min(int(score), 100)

def scan_ai_dna(extract_dir: str) -> dict:
    """
    Returns a summary dict with overall AI confidence and per-file breakdown.
    Does NOT return issues list — this is a separate top-level metric.
    """
    per_file = []
    IGNORED = {'node_modules', 'venv', '__pycache__', '.git', 'dist', 'build'}

    for root, dirs, files in os.walk(extract_dir):
        dirs[:] = [d for d in dirs if d not in IGNORED and not d.startswith('.')]
        for f in files:
            ext = os.path.splitext(f)[1].lower()
            if ext not in SOURCE_EXTS:
                continue
            path = os.path.join(root, f)
            try:
                with open(path, 'r', encoding='utf-8', errors='ignore') as fh:
                    content = fh.read()
                if len(content.strip()) < 50:
                    continue
                stats = _analyze_file(content)
                confidence = _compute_ai_confidence(stats)
                rel = os.path.relpath(path, extract_dir).replace('\\', '/')
                per_file.append({
                    'file': rel,
                    'confidence': confidence,
                    'lines': stats['total_lines']
                })
            except Exception:
                continue

    if not per_file:
        return {'overall_confidence': 0, 'files': [], 'verdict': 'Unknown'}

    # Weight by file size
    total_lines = sum(f['lines'] for f in per_file) or 1
    weighted = sum(f['confidence'] * f['lines'] for f in per_file) / total_lines
    overall = int(weighted)

    verdict = (
        'Almost certainly AI-generated' if overall >= 80 else
        'Likely AI-generated' if overall >= 60 else
        'Mixed (Human + AI)' if overall >= 35 else
        'Likely Human-written'
    )

    per_file.sort(key=lambda x: x['confidence'], reverse=True)

    return {
        'overall_confidence': overall,
        'files': per_file[:10],  # top 10 most AI-looking files
        'verdict': verdict
    }
